### ISSUE TITLE
Body now rotates around the head when you turn left/right.

### ISSUE THREAD

**Issue by ThreadOfFate** [SlimeVR/SlimeVR-Tracker-ESP#198]
Issue seems to be introduced between these commits.
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/commit/9d93df6e6a0f3c0f68466669a100667925b4d801
https://github.com/SlimeVR/SlimeVR-Tracker-ESP/commit/b8bd02e60d01312634fa71b12512b7556cd0dedf

Both reports of this issue are from ICM 20948 users.

![VRChat_1920x1080_2022-10-02_01-09-12 796](https://user-images.githubusercontent.com/37180802/193473102-395dbfca-2595-4300-afcc-d0c403aeb242.png)
![VRChat_1080x1920_2022-10-02_00-36-33 812](https://user-images.githubusercontent.com/37180802/193473112-0616071b-0f9a-485f-ab71-788651cb684b.png)

**Comment by TheDevMinerTV** [comment]
These are the changes between those commits: https://github.com/SlimeVR/SlimeVR-Tracker-ESP/compare/9d93df6e6a0f3c0f68466669a100667925b4d801..b8bd02e60d01312634fa71b12512b7556cd0dedf

**Comment by unlogisch04** [comment]
I do expect this line to be the reason for the change. https://github.com/SlimeVR/SlimeVR-Tracker-ESP/compare/b8bd02e60d01312634fa71b12512b7556cd0dedf..9d93df6e6a0f3c0f68466669a100667925b4d801#diff-d057e2d1cf9af1b161e90eb4c9f63baa4658f80e6351f90a862c5a14dadd4622R410

**Comment by unlogisch04** [comment]
I work on this https://github.com/unlogisch04/SlimeVR-Tracker-ESP/tree/ICM20948_MagnetometerFix
