### ISSUE TITLE
Wifi credentials doesn't save after reset

### ISSUE THREAD

**Issue by adigyran** [SlimeVR/SlimeVR-Tracker-ESP#20]
Wifi credentials set by serial command don't recover after reset. Have to set each time (and also impossible to use because at the same moment i disconnect usb, it already gone)
Only hardcode credentials work fine

Tested on 2 node mcu v2

**Comment by Kamilake** [comment]
Same here..
Unlike the ESP32, the ESP8266 Library does not automatically save the wifi password. 
Hardcoding is not recommended as it is a security vulnerability.
I didn't find any code to keep wifi password in that source code (If that part is not resolved, I'll try fix it to store credentials in NVRAM)

**Comment by Eirenliel** [comment]
Seems like the problem was fixed.
