### ISSUE TITLE
Trackers not connecting without WiFi reboot

### ISSUE THREAD

**Issue by ButterscotchV** [SlimeVR/SlimeVR-Tracker-ESP#203]
Discussion is on Discord: https://discord.com/channels/817184208525983775/1027559999574114376

There seems to be an issue with specific routers where a reboot is required to get Slime trackers to connect.

Routers known to have this issue:
- TP-Link Archer C4000 (AC4000)

Routers that might be fixed by setting `WiFi.SetPhyMode(WIFI_PHY_MODE_11G)`:
- TP-Link Archer AXE75 (AXE5400)

Add `WiFi.SetPhyMode(WIFI_PHY_MODE_11G)` to `src/network/wifihandler.cpp:WiFiNetwork::setUp()` like in the following image
![image](https://user-images.githubusercontent.com/5095026/196085618-789377eb-9b3e-4086-b0af-51918bdfff22.png)
[(From Kamilake)](https://discord.com/channels/817184208525983775/1027559999574114376/1027825065057865738)

Routers that might have this issue:
- ASUS RT-AX56U
- ASUS RT-AC66U
- ASUS RT-AC68U
- ASUS ROG AX11000
- ASUS ROG AXE11000
- ASUS ZenWiFi AX Mini (XD4)

Routers that require to be set to "Legacy" Wireless Mode:
- ASUS TUF-AX5400
- ASUS RT-AX55
- ASUS RT-AX82U
- ASUS RT-AX88U
- ASUS RT-AX92U

![Screenshot_20221007-002639.jpg](https://user-images.githubusercontent.com/5095026/194527043-3d8f6600-81b8-4a15-a767-e42420f89336.jpg)
[(From Loler920a-Frank)](https://discord.com/channels/817184208525983775/1027559999574114376/1027572725277011978)

Routers that do **not** have this issue:
- ASUS RT-AX58U

**Comment by Eirenliel** [comment]
seem to be related: https://github.com/esp8266/Arduino/issues/8412

**Comment by ButterscotchV** [comment]
Stumbled upon a possible solution from the esp8266 thread, apparently these issues are fixed in the latest esp8266 Arduino version and you can switch to that in PlatformIO by changing the board config in `platformio.ini`

From
```ini
[env:esp12e]
platform = espressif8266
board = esp12e
; Comment out this line below if you have any trouble uploading the firmware
; and if it has a CP2102 on it (a square chip next to the usb port): change to 3000000 (3 million) for even faster upload speed
upload_speed = 921600
```
to
```ini
[env:esp12e]
platform = espressif8266
board = esp12e
; Comment out this line below if you have any trouble uploading the firmware
; and if it has a CP2102 on it (a square chip next to the usb port): change to 3000000 (3 million) for even faster upload speed
upload_speed = 921600
platform_packages =
  platformio/framework-arduinoespressif8266 @ https://github.com/esp8266/Arduino.git
```

**Comment by ButterscotchV** [comment]
Should be fixed with release 0.3.0

**Comment by ButterscotchV** [comment]
Re-opening at the request of @nullstalgia, the source of the problem still isn't quite found

**Comment by TheGuardianWolf** [comment]
![image](https://user-images.githubusercontent.com/8168401/212480564-e0f375e5-440b-4ddf-b83d-bac38007c38b.png)

I am able to connect without the fallback by switching to 20MHz simply. Perhaps this chip is not compatible with 40MHz? ESP32 is fine though.

Before on 20/40MHz
![image](https://user-images.githubusercontent.com/8168401/212480699-c0c62ff0-f9ac-4c3d-9ac4-06daf87767db.png)


After:
![image](https://user-images.githubusercontent.com/8168401/212480714-3f0bba57-7c12-4a5d-814a-c2b365e7b459.png)
