### ISSUE TITLE
[INFO ] [MPU9250Sensor:0] Connected to MPU9250 (reported device ID 0x75) at address 0x68

### ISSUE THREAD

**Issue by yunlancn** [SlimeVR/SlimeVR-Tracker-ESP#204]
[INFO ] [MPU9250Sensor:0] Connected to MPU9250 (reported device ID 0x75) at address 0x68

why my mpu9250 device ID is 0x75
if i modify mpu9250.cpp 0x71 to 0x75
it can start calibration, but 

[DEBUG] [MPU9250Sensor:0] [INFO] Magnetometer calibration matrix:
[DEBUG] [MPU9250Sensor:0] {
[DEBUG] [MPU9250Sensor:0]   -nan, -nan, -nan, -nan
[DEBUG] [MPU9250Sensor:0]   nan, -nan, -nan, -nan
[DEBUG] [MPU9250Sensor:0]   nan, -nan, -nan, -nan
[DEBUG] [MPU9250Sensor:0] }

calibration matrix is nan

Sorry I am from China, My English isn't good

**Comment by Disappear9** [comment]
淘宝买的便宜芯片吧？I2C地址0x75说明是假的9250，退货吧，或者配置成6500/6050用

Fake 9250, RMA it, or configure it as 6500/6050.
