### ISSUE TITLE
MPU9250 does not work properly after this commit

### ISSUE THREAD

**Issue by TinyOra** [SlimeVR/SlimeVR-Tracker-ESP#218]
I asked in discord a month ago but no one seemed to notice https://discord.com/channels/817184208525983775/1054741415579619430

The commits: fd3e463a9c60411715ed3ff2b333158ada86c225

After flashing ,The 9250 's yaw data is very confusing, If I rotate to the left, the data increases first and then decreases after a while,  and tends to return to its original value. If I rotate to the right, just the opposite

In actual use, the tracker rotates at weird angles,so it is basically unuseable

Rollback to the previous version everything is fine

I have compared the code , it seems that enabling Mahoney / Magiwick causing the problem btw

**Comment by Nuzair46** [comment]
Had the same issue for me too.

**Comment by unlogisch04** [comment]
I have the same observed with BMI160.

**Comment by Nuzair46** [comment]
Can anyone confirm if v0.3.2 fixed this?

**Comment by unlogisch04** [comment]
No it will be in v0.3.3 currently it is in main
