### ISSUE TITLE
ESP disconnects from the server when the Wifi window closes

### ISSUE THREAD

**Issue by MightyGood** [SlimeVR/SlimeVR-Tracker-ESP#23]
When setting wifi credentials, the ESP will connect with the Wifi window open. When you close the Wifi window the LED on the ESP flashes quickly, then it disconnects from the server.

It almost seems like closing the Wifi windows sends a restart command to the ESP.

**Comment by adigyran** [comment]
Reconnects immediately after that

**Comment by unlogisch04** [comment]
Can not reproduce. Also i think if it restarts when the USB is disconnected or the WiFi window closed, it should be not a problem.
I think this issue can be closed.

**Comment by Eirenliel** [comment]
Agree.
