### ISSUE TITLE
Esp doesn't reconnect automatically when wifi connection is lost

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Tracker-ESP#25]
Possibly something was broken during last changes in wifi code, or it never worked.

**Comment by LensError** [comment]
it has never worked for me

**Comment by Eirenliel** [comment]
This should be the fix: https://github.com/SlimeVR/SlimeVR-Tracker-ESP/commit/85a0f5581f447ebc9a2ff9d3867c7f36e5433e7a
