### ISSUE TITLE
v0.3.3 is not reliable with BNO08X

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Tracker-ESP#264]
See [thread in Discord](https://discord.com/channels/817184208525983775/1133471817915449514). A lot of the time BNO085 will not be recognized by firmware and the tracker will not boot. This happens after upgrade [from 0.3.2 to 0.3.3](https://github.com/SlimeVR/SlimeVR-Tracker-ESP/compare/v0.3.2...v0.3.3), so the problem is in changes there.

**Comment by ButterscotchV** [comment]
Fairly certain this has been full resolved by #268
