### ISSUE TITLE
package.json  missing

### ISSUE THREAD

**Issue by jacob10001** [SlimeVR/SlimeVR-Tracker-ESP#304]
i keep getting this error message.
"MissingPackageManifestError: Could not find one of 'package.json' manifest files in the package"

**Comment by TheDevMinerTV** [comment]
What program is reporting this error?

**Comment by jacob10001** [comment]
I'm using platformio in vs code

**Comment by unlogisch04** [comment]
I don't think that it is a problem with the project. As a Project it is not common to need a "package.json".

Can you give more detailed information?
 - Did you restart your computer after installing VS Code, GIT, Platform IO?
 - Did you give PlatformIO enough time to download all its needs? 
 - How did you download the Project?
 - What commands did you run that the error did come up?

**Comment by jacob10001** [comment]
i did not restart my computer after installing everything.
i tried two ways. downloading the .zip manually, and using the link to github.
after ensuring all necessary files were correct using the guide
it was when i clicked the build button that the error message appeared

**Comment by unlogisch04** [comment]
Closing this issue. Reopen it if it is still a problem.
