### ISSUE TITLE
Question regarding software-hardware

### ISSUE THREAD

**Issue by AlexNikMak** [SlimeVR/SlimeVR-Tracker-ESP#312]
Hello! (I am new to git and slimevr)

I have a question regarding hardware. I would like to make my own all-in-one board that should facilitate the main wifi controller, IMU, voltage and battery controller, etc.
1. What is minimal specs fore main wifi controller. I mean flash, ram, cpu clock and other.
2. Have someone tried working with BMI270? To clarify, slimevr IMU should have 3D accelerometer and 3D gyroscope to properly work.
3. Have someone tride making more than 1 extension per Maine wifi controller? Is it supported by software? Is Esp3266 wifi module capable of transmitting all of this info.
4. What load slimevr puts on wifi router in case of FBT (16 IMUs)?Should I consider obtaining a separate router?
5. Is using more than (16 IMUs) make any significant difference in overall trading performance?If it supported.
6. Can 1 pc with 1 slimevr server track 2 or more people simultaneously.

**Comment by Vyolex** [comment]
Would advice joining the [discord server](https://discord.com/invite/slimevr), it is very valuable when making the trackers DIY. There is also already community made pcbs which you might want to take a look at on there!

In short:
  1. The firmware fits on pretty much any ESP8266 or ESP32 
```
RAM:   [=====     ]  54.2% (used 44368 bytes from 81920 bytes)
Flash: [=====     ]  52.8% (used 551139 bytes from 1044464 bytes)
```
  2. BMI270 has been experimented with and afaik has gotten positive reactions from the community, although it has not been added to the main firmware yet seemingly
  3. There have been people experimenting with this, octoslime is a hardware implementation that uses multiplexers, there is also the branch from sctanf that adds support in software (also not in the main firmware yet afaik)
  4. Bandwidth/throughput wise slime uses almost nothing, tho they do add devices and are somewhat sensitive to interferance. Having a dedicated router is not nessesary at all, but it is a benefit especially if the signal is weak where you plan to use them.
  5. Not sure what you mean, I think we have support for 20 locations atm, usually 3 of these are ocupied by the heaset and the controllers. So you can use up to 20 atm, my personal preference is using 10 trackers (8+2 configuration). I'd refer to the [documentation](https://docs.slimevr.dev/) if you want more information on that though.
  6. No, a server instance can only track a single person at a time. Running multiple servers on the same machine is also not supported atm without manually changing things. In fact currently there is no great way to have more than one person using slimes on the same network.

Hope this answered some of your questions, I'm closing this issue now as it has nothing to do with the development, if you want more information I'd encourage you to join the discord!
