### ISSUE TITLE
Building firmware using GitHub Actions

### ISSUE THREAD

**Issue by adigyran** [SlimeVR/SlimeVR-Tracker-ESP#35]
https://github.com/SlimeVR/SlimeVR-Server/issues/76 To implement that it would be useful to build different types of firmware (for different boards) with github actions, and server could upload it by itself.
https://docs.platformio.org/en/latest/integration/ci/github-actions.html
gonna experiment with this

**Comment by Eirenliel** [comment]
We should genreally setup CI for testing purposes. It should at least try to compile for BNO085 and both ESP8266 and ESP32. There are some compilation erros that sneak into main because we don't test for both usually, only the one we work with.

**Comment by adigyran** [comment]
assign me for that

**Comment by Eirenliel** [comment]
I don't need to assign you to work on it, just do it :P there was also someone else who wanted to, but I don't remember who...

**Comment by TheDevMinerTV** [comment]
Done
