### ISSUE TITLE
Low battery LED signal

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Tracker-ESP#39]
Should start blinking LED when battery level drops too low (like 3.3v probably?)

**Comment by adigyran** [comment]
how about using 2 color led?

**Comment by Eirenliel** [comment]
For prodution - maybe, if there is any space on the board, but it has to be compatible with DIY, which has only 1 led.

**Comment by adigyran** [comment]
but ppl would not see blinking in VR, anyways it would be neat feature for like 10%-5% battery remaining

**Comment by sctanf** [comment]
At 3.3v the tracker should be turned off, maybe 3.5v is better to begin notifying about low battery

**Comment by Kamilake** [comment]
That's desirable, and intuitive option.
However two-color LED or two LEDs look good, too)
I think someone will use a full-color LED in DIY.

**Comment by Eirenliel** [comment]
Implemented.
