### ISSUE TITLE
Per-sensor configuration

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Tracker-ESP#41]
This is required for #32 and overal MPU support (#14), as well as for enabling and disabling magnetometers. Need to adjust protocol and configuration storage to implement recieving, sending, and storing of per-tracker configuration, that can store such things as magnetometer status, calibration data, etc.

This does not superceed the usage of defines to configure hardware setup.

**Comment by unlogisch04** [comment]
should be solved with https://github.com/SlimeVR/SlimeVR-Tracker-ESP/pull/134

**Comment by Eirenliel** [comment]
This was actually solved, magnetometer configuration and sending settings from the server should be in #230.
