### ISSUE TITLE
Add wifi signal strength indicator

### ISSUE THREAD

**Issue by deiteris** [SlimeVR/SlimeVR-Tracker-ESP#44]
It would be useful to see signal strength to better diagnose connectivity issues. Arduino framework provides a method to get signal strength of the current connection: https://www.arduino.cc/en/Reference/WiFiRSSI

**Comment by Kamilake** [comment]
Yes! it certainly works as necessary and expected.
I'm thinking about what to do to make it easier for users to see intuitively)

I am currently testing by inserting the following code into the clientUpdate function.
```cpp
if (WiFi.status() != WL_CONNECTED) {
    Serial.println("DISCONNECTED");
}
else {
int rssi = WiFi.RSSI();
    Serial.print("Signal Strenth: ");
    Serial.print(100+rssi);
    Serial.print("% (");
    Serial.print(rssi);
    Serial.println(")");
}
```
(RSSI value is not linear so I think there is a limit to displaying it directly as %)

**Comment by TheButlah** [comment]
Is it better to display signal strength, or instead just latency + dropped packet rate?

**Comment by Kamilake** [comment]
> Is it better to display signal strength, or instead just latency + dropped packet rate?

I'm curious about that too
For experts with DIY, it will be easier to understand and more useful to show dropped+rssi
But for beginners or ordinary people who don't, signal strength% + latency will be friendly.

**Comment by TheButlah** [comment]
% of packets dropped can be mapped to a wifi signal indicator just as well as a wifi signal strength can

**Comment by Eirenliel** [comment]
we can't measure dropped packets, since they're not tracked currently. we can start tracking them, but also eh... latency is displayed already, that's PING. signal strength can be added, ye, i'm up for this

**Comment by Eirenliel** [comment]
Implemented.
