### ISSUE TITLE
Implement proper serial commands handling

### ISSUE THREAD

**Issue by Eirenliel** [SlimeVR/SlimeVR-Tracker-ESP#6]
Need to handle a few commands from serial port for debug, testing and configuration. Need to implement the system as a whole, and a few necessary commands:

* [ ] Health report
* [x] Reboot
* [x] Factory reset
* [x] Set up WiFi credentials
* [x] Getting firmware config

**Comment by adigyran** [comment]
can you add current tracker IP command also?

**Comment by Kamilake** [comment]
Reboot, Factory reset seems to have been completed in #101 #102.

**Comment by Bluscream** [comment]
A "GET CONFIG" command would be nice as well

**Comment by Eirenliel** [comment]
True.

**Comment by loucass003** [comment]
What is needed in the health statuts ?
what infos do we want to put in it

**Comment by Eirenliel** [comment]
Which server it is connected to, status of IMUs, at the very least.

**Comment by loucass003** [comment]
Im gonna work on the last one this week, while i am waiting for new gui stuff

**Comment by Eirenliel** [comment]
GET HEALTH should be GET TEST with some additional info, with all IMUs and server connection status.
