### ISSUE TITLE
Brownout Sensor was detected

### ISSUE THREAD

**Issue by Pablotir** [SlimeVR/SlimeVR-Tracker-ESP#61]
Im using an esp32-wroom and a MPU6050. I haven't built the tracker to use an external power source and its running solely on USB. The error goes away when I disconnect the MPU but I get another error that it can't detect SCL or SDA pins so not much space to do anything.

**Comment by Eirenliel** [comment]
Hi. Please direct hardware-related questions to our #diy discord channel in https://slimevr.dev/discrod, there are many more people that will be able to help you in no time.

**Comment by Pablotir** [comment]
I've tried for the last 3 days but no one replies to my question
