### ISSUE TITLE
ESP 8266 / 32

### ISSUE THREAD

**Issue by kenthinson** [SlimeVR/SlimeVR-Tracker-ESP#62]
Any advantage one over the other? Any future feature plans that would require the 32? Just future planning here thanks :)

**Comment by AtlasTheProto** [comment]
This is really a question better suited for a discord discussion, but the main thing of note with the ESP32 is its dual I2C busses, which could allow for more than two extensions, if supported on the firmware.

**Comment by Eirenliel** [comment]
There might be support of bluetooth in the future if anyone implements it, or additional I2C busses to connect more trackers to one MCU. But either is not planned to be done by me, so it's not official plan.
